name: first workflow
on: workflow_dispatch
jobs:
  first-job:
     runs-on: ubuntu-latest
     steps:
        - name: print greeting
          run: echo "hello"
        - name: print godbaye
          run: echo "Done - Bye" 
